# Generated by Django 2.1.2 on 2019-01-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('commend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repcontext', models.CharField(max_length=250)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('demandid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commend.Demand')),
                ('uerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Replytoreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrepcontext', models.CharField(max_length=250)),
                ('rcreatetime', models.DateTimeField(auto_now=True)),
                ('replyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commend.Reply')),
                ('ruerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Userinfo')),
            ],
        ),
    ]
