# Generated by Django 2.1.2 on 2018-12-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
